name: R-CMD-Check
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

permissions: read-all

concurrency:
  group: R-CMD-check-${{ github.ref }}
  cancel-in-progress: true

env:
  RGL_USE_NULL: "TRUE"

jobs:
  R-CMD-check:
    strategy:
      fail-fast: false
      matrix:
        config:
          # Non-Docker configurations
          - { os: macos-latest, r: "release" }
          - { os: windows-latest, r: "release" }
          - { os: ubuntu-latest, r: "release" }
          - { os: ubuntu-latest, r: "devel", http-user-agent: "release" }
          - { os: ubuntu-latest, r: "oldrel-1" }
    runs-on: ${{ matrix.config.os }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Install Pandoc
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      # Common R setup for all configurations
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      - name: Setup R Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck

      # Run standard R CMD check (non-Docker)
      - name: Run R CMD check (standard)
        uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'

  R-CMD-check-fs:
    strategy:
      fail-fast: false
      matrix:
        config:
          - { r: "4.5.0", fs: "8.0.0" }
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4


      # FreeSurfer + Docker-based checks
      - name: Check if Docker Image Exists
        id: image_check
        run: |
          IMAGE_TAG="r_${{ matrix.config.r }}-fs_${{ matrix.config.fs }}"
          FULL_IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/${{ github.repository }}/r-freesurfer:${IMAGE_TAG}"
          echo "Checking if image exists: $FULL_IMAGE_NAME"
          echo "image_exists=false" >> $GITHUB_ENV
          if docker pull $FULL_IMAGE_NAME; then
            echo "image_exists=true" >> $GITHUB_ENV
          fi

      - name: Trigger Image Build Workflow
        if: env.image_exists == 'false'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split("/");
            await github.rest.actions.createWorkflowDispatch({
              owner,
              repo,
              workflow_id: "build-fs-r-image.yml",
              ref: "master",
              inputs: {
                r_version: process.env.MATRIX_CONFIG_R,
                fs_version: process.env.MATRIX_CONFIG_FS,
                push: true
              }
            });

      - name: Pull or Wait for Image Build Completion
        run: |
          echo "Ensuring the Docker image is available..."
          IMAGE_TAG="r_${{ matrix.config.r }}-fs_${{ matrix.config.fs }}"
          FULL_IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/${{ github.repository }}/r-freesurfer:${IMAGE_TAG}"
          while ! docker pull $FULL_IMAGE_NAME; do
            echo "Image not available yet. Retrying in 600 seconds..."
            sleep 600
          done

      - name: Run R CMD Check in Docker
        run: |
          docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          ghcr.io/${{ github.repository_owner }}/${{ github.repository }}/r-freesurfer:r_${{ matrix.config.r }}-fs_${{ matrix.config.fs }} \
          bash -c "cd /workspace && R CMD check ."

      - name: Archive Logs (Docker-based failure)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: r-cmd-check-logs
          path: /workspace/*.Rcheck

